---
# Installs Java

- name: Add apt-repo for Java dependancies
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept Oracle license terms 
  debconf: >-
    name='oracle-java8-installer'
    question='shared/accepted-oracle-license-v1-1'
    value='true' vtype='select'

- name: Install Java Required Packages
  apt: name={{ item }} state=present
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - maven
    
- name: Select Oracle Java as Default
  alternatives: name=java path={{ java_home }}/jre/bin/java
