sudo: true
language: python

matrix:
    fast_finish: true

branches:
  only:
    - /master/

install:
  - pip install mkdocs
  - pip install mkdocs-material

script:
  - mkdocs build --clean
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
