language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

branches:
  only:
    - 7.x-2.x
    - sprint-002

before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/drupal/islandora/tests/scripts/travis_setup.sh

script:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - cd $TRAVIS_BUILD_DIR/services
  - $TRAVIS_BUILD_DIR/install/scripts/align_branches.sh "$BRANCH"
  - composer update
  - cd $HOME/drupal-*
  - ant -buildfile sites/all/modules/islandora/drupal/islandora/build.xml lint
  - $ISLANDORA_DIR/drupal/islandora/tests/scripts/line_endings.sh sites/all/modules/islandora/drupal/islandora sites/all/modules/islandora/drupal/islandora_apachesolr sites/all/modules/islandora/drupal/islandora_basic_image sites/all/modules/islandora/drupal/islandora_collection sites/all/modules/islandora/drupal/islandora_dc sites/all/modules/islandora/drupal/islandora_mods sites/all/modules/islandora/drupal/islandora_rdf_mapping_service
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora islandora_apachesolr islandora_basic_image islandora_collection islandora_dc islandora_mods islandora_rdf_mapping_service
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora/drupal/islandora sites/all/modules/islandora/drupal/islandora_apachesolr sites/all/modules/islandora/drupal/islandora_basic_image sites/all/modules/islandora/drupal/islandora_collection sites/all/modules/islandora/drupal/islandora_dc sites/all/modules/islandora/drupal/islandora_mods sites/all/modules/islandora/drupal/islandora_rdf_mapping_service
  - drush test-run --uri=http://localhost:8081 Islandora
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - cd $TRAVIS_BUILD_DIR/camel
  - mvn install -B -V
  - mvn javadoc:jar
  - mvn javadoc:test-aggregate
  - php vendor/bin/phpcs --standard=PSR2 services/src
  - php vendor/bin/phpcs --standard=PSR2 services/TransactionService/src
  - php vendor/bin/phpcs --standard=PSR2 services/ResourceService/src
  - php vendor/bin/phpcs --standard=PSR2 services/TransactionService/src
