sudo: true
language: python

matrix:
    fast_finish: true

branches:
  only:
    - /main/

install:
  - pip install mkdocs
  - pip install git+https://${GITHUB_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
  - pip install mkdocs-git-revision-date-localized-plugin

script:
  - mkdocs build --clean
  
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
