site_name: Islandora CLAW
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora CLAW

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora-CLAW/CLAW

theme: material

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'

pages:

- User Documentation:
    - 'Introduction to Islandora CLAW': 'user-documentation/intro-to-claw.md'
    - 'Islandora CLAW for 1.x Users': 'user-documentation/2xfor1x.md'
- Technical Documentation:
    - 'Minimum Viable Product': 'mvp/mvp_doc.md'
    - 'How to build documenation': 'technical-documentation/docs-build.md'
    - 'Semantic Versioning Policy': 'technical-documentation/versioning.md'
- Components: 
    - 'Islandora CLAW': 'index.md'
    - 'Alpaca': 'alpaca/README.md'
    - 'Islandora (Drupal module)': 'islandora/README.md'
- Installation:
    - 'Installation (Vagrant)': 'claw_vagrant/README.md'
- Contributing:
    - 'How to contribute': 'contributing/CONTRIBUTING.md'
    - 'Committers': 'contributing/committers.md'
    - 'Hacking on Islandora': 'contributing/hacking-on-islandora.md'
- Migration:
    - 'Migration': 'migration/migration.md'
    - 'Fedora namespace predicates': 'migration/fedora-namespace-predicates.md'
    - 'Islandora namespace predicates': 'migration/islandora-namespace-predicates.md'
