site_name: Islandora 8
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora 8

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora/documentation
edit_uri: 'edit/main/docs/'

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/claw.png'
  language: 'en'
markdown_extensions:
  - admonition

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/islandora'

nav:
  - Overview: 'index.md'
  - Installation:
      - 'Component Overview': 'installation/component_overview.md'
      - 'Ansible Playbook': 'installation/playbook.md'
      - 'Docker Compose (ISLE-DC)': 'installation/docker-compose.md'
      - Manual Installation:
        - 'Introduction': 'installation/manual/introduction.md'
        - 'Preparing a LAPP Webserver': 'installation/manual/preparing_a_webserver.md'
        - 'Installing Composer, Drush, and Drupal': 'installation/manual/installing_composer_drush_and_drupal.md'
        - 'Installing Tomcat and Cantaloupe': 'installation/manual/installing_tomcat_and_cantaloupe.md'
        - 'Installing Fedora, Syn, and Blazegraph': 'installation/manual/installing_fedora_syn_and_blazegraph.md'
        - 'Installing Solr': 'installation/manual/installing_solr.md'
        - 'Installing Crayfish': 'installation/manual/installing_crayfish.md'
        - 'Installing Karaf and Alpaca': 'installation/manual/installing_karaf_and_alpaca.md'
        - 'Configuring Drupal': 'installation/manual/configuring_drupal.md'
  - User Documentation:
      - 'Introduction': 'user-documentation/user-intro.md'
      - 'Video Documentation': 'user-documentation/video-docs.md'
      - 'Intro to Linked Data': 'user-documentation/intro-to-ld-for-islandora-8.md'
      - Content in Islandora 8:
        - 'Resource Nodes': 'user-documentation/resource-nodes.md'
        - 'From Objects to Resource Nodes': 'user-documentation/objects_to_resource_nodes.md'
        - 'Media': 'user-documentation/media.md'
        - 'Collections': 'user-documentation/collections.md'
        - 'Paged Content': 'user-documentation/paged-content.md'
        - 'Metadata': 'user-documentation/metadata.md'
      - How-To:
        - 'Create a Resource Node': 'user-documentation/creating-a-node.md'
        - 'Modify or Create a Content Type': 'user-documentation/content_types.md'
        - 'Create or Update a View': 'user-documentation/create_update_views.md'
        - 'Add a New User': 'user-documentation/users.md'
      - 'Searching': 'user-documentation/searching.md'
      - 'Context': 'user-documentation/context.md'
      - 'Blocks': 'user-documentation/blocks.md'
      - 'Usage Stats': 'user-documentation/usage-stats.md'
      - 'Versioning': 'user-documentation/versioning.md'
      - 'Multilingual': 'user-documentation/multilingual.md'
      - 'Accessibility': 'user-documentation/accessibility.md'
      - Integrations:
        - 'Extending Islandora': 'user-documentation/extending.md'
        - 'IIIF': 'user-documentation/iiif.md'
        - 'OAI-PMH': 'user-documentation/oai.md'
  - Repository Administrator Documentation:
      - 'RDF Generation': 'islandora/rdf-mapping.md'
      - 'Drupal Bundle Configurations': 'islandora/drupal-bundle-configurations.md'
  - System Administrator Documentation:
    - 'Installing Modules': 'technical-documentation/install-enable-drupal-modules.md'
    - 'Updating Drupal': 'technical-documentation/updating_drupal.md'
    - 'Uploading large files': 'technical-documentation/uploading-large-files.md'
  - Developer Documentation:
    - 'Architecture Diagram': 'technical-documentation/diagram.md'
    - REST Documentation:
      - 'Introduction': 'technical-documentation/using-rest-endpoints.md'
      - 'GET': 'technical-documentation/rest-get.md'
      - 'POST/PUT': 'technical-documentation/rest-create.md'
      - 'PATCH': 'technical-documentation/rest-patch.md'
      - 'DELETE': 'technical-documentation/rest-delete.md'
      - 'Signposting': 'technical-documentation/rest-signposting.md'
    - Tests:
      - 'Running Tests': 'technical-documentation/running-automated-tests.md'
      - 'Testing Notes': 'technical-documentation/testing-notes.md'
    - 'Updating drupal-project': 'technical-documentation/drupal-project.md'
    - 'Flysystem': 'technical-documentation/flysystem.md'
    - 'JWT Authentication': 'technical-documentation/jwt.md'
    - 'Versioning Policy': 'technical-documentation/versioning.md'
    - 'How to Build Documentation': 'technical-documentation/docs-build.md'
    - 'Adding back ?_format=jsonld': 'technical-documentation/adding_format_jsonld.md'
    - 'Updating a `deb` and adding it to Lyrasis PPA': 'technical-documentation/ppa-documentation.md'
    - Alpaca:
      - 'Alpaca Technical Stack': 'alpaca/alpaca-technical-stack.md'
      - 'Alpaca Tips': 'technical-documentation/alpaca_tips.md'
  - Migration:
      - 'Migration Overview': 'technical-documentation/migration-overview.md'
      - 'CSV': 'technical-documentation/migrate-csv.md'
      - 'Islandora 7': 'technical-documentation/migrate-7x.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - Virtual Machines:
        - 'Hacking on Islandora': 'contributing/hacking-on-islandora.md'
        - 'Resizing a VM': 'technical-documentation/resizing_vm.md'
      - 'Checking Coding Standards': 'technical-documentation/checking-coding-standards.md'
      - 'Contributing Workflow': 'contributing/contributing-workflow.md'
      - 'Documentation Style Guide': 'contributing/docs_style_guide.md'
      - 'Committers': 'contributing/committers.md'
  - Glossary: 'user-documentation/glossary.md'
