site_name: Islandora 8
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora 8

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora/documentation

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/claw.png'
  language: 'en'
markdown_extensions:
  - admonition

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'assets/claw.png'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/islandora'

pages:
  - Summary: 'index.md'
  - Installation: 'installation.md'
  - User Documentation:
      - 'Introduction': 'user-documentation/user-intro.md'
      - 'Nodes': 'user-documentation/objects.md'
      - 'Media': 'user-documentation/media.md'
      - 'Make an Image': 'user-documentation/creating-an-object.md'
      - 'Collections': 'user-documentation/collections.md'
      - 'Metadata': 'user-documentation/metadata.md'
      - 'Content Types': 'user-documentation/content_types.md'
      - 'Searching': 'user-documentation/searching.md'
      - 'Context': 'user-documentation/context.md'
      - 'Views': 'user-documentation/create_update_views.md'
      - 'Users': 'user-documentation/users.md'
      - 'Blocks': 'user-documentation/placing-blocks.md'
      - 'Usage Stats': 'user-documentation/usage-stats.md'
      - 'Multilingual': 'user-documentation/multilingual.md'
  - Administrator Documentation:
      - 'RDF Generation': 'islandora/rdf-mapping.md'
  - Developer Documentation:
    - REST Documentation:
      - 'Introduction': 'technical-documentation/using-rest-endpoints.md'
      - 'GET': 'technical-documentation/rest-get.md'
      - 'POST/PUT': 'technical-documentation/rest-create.md'
      - 'PATCH': 'technical-documentation/rest-patch.md'
      - 'DELETE': 'technical-documentation/rest-delete.md'
      - 'Signposting': 'technical-documentation/rest-signposting.md'
    - 'Installing Modules': 'technical-documentation/install-enable-drupal-modules.md'
    - 'Running Tests': 'technical-documentation/running-automated-tests.md'
    - 'Flysystem': 'technical-documentation/flysystem.md'
    - 'JWT Authentication': 'technical-documentation/jwt.md'
    - 'Versioning Policy': 'technical-documentation/versioning.md'
    - 'Documentation Style Guide': 'technical-documentation/docs_style_guide.md'
    - 'How to Build Documentation': 'technical-documentation/docs-build.md'
    - 'Testing Notes': 'technical-documentation/testing-notes.md'
    - 'Adding back ?_format=jsonld': 'technical-documentation/adding_format_jsonld.md'
    - 'Updating a `deb` and adding it to Lyrasis PPA': 'technical-documentation/ppa-documentation.md'

  - Migration:
      - 'CSV': 'technical-documentation/migrate-csv.md'
      - 'Islandora 7': 'technical-documentation/migrate-7x.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - 'Committers': 'contributing/committers.md'
