site_name: Islandora CLAW
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora CLAW

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora-CLAW/CLAW

theme: material
markdown_extensions:
  - admonition

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'assets/claw.png'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/islandora'

nav:
  - Summary: 'index.md'
  - User Documentation:
      - 'Intro': 'user-documentation/user-intro.md'
      - 'Objects are Nodes': 'user-documentation/objects.md'
      - 'Metadata are Fields': 'user-documentation/metadata.md'
      - 'Datastreams are Media': 'user-documentation/datastreams.md'
      - 'Derivatives': 'user-documentation/derivatives.md'
      - 'Organizing your Collections': 'user-documentation/collections.md'
      - 'Access Control': 'user-documentation/access-control.md'
      - 'Objects in Fedora/RDF': 'user-documentation/fedora-rdf.md'
      - 'Introduction to Islandora CLAW [old]': 'user-documentation/intro-to-claw.md'
      - 'Islandora CLAW for 1.x Users [old]': 'user-documentation/CLAWfor1x.md'
      - 'Introduction to Linked Data for CLAW [old]': 'user-documentation/intro-to-ld-for-claw.md'
      - 'Getting Started with Islandora CLAW [old]': 'user-documentation/getting-started-with-islandora-claw.md'
  - Technical Documentation:
      - 'Minimum Viable Product': 'mvp/mvp_doc.md'
      - 'How to build documenation': 'technical-documentation/docs-build.md'
      - 'Syncing Drupal Project': 'technical-documentation/drupal-project.md'
      - 'Versioning Policy': 'technical-documentation/versioning.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - 'Committers': 'contributing/committers.md'
      - 'Hacking on Islandora': 'contributing/hacking-on-islandora.md'
  - Migration:
      - 'Migration': 'migration/migration.md'
      - 'Fedora namespace predicates': 'migration/fedora-namespace-predicates.md'
      - 'Islandora namespace predicates': 'migration/islandora-namespace-predicates.md'
