---
# Common tasks for all hosts

- name: Upgrade OS
  apt: upgrade=yes update_cache=yes cache_valid_time=3600

- name: Install Common Software Packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - software-properties-common
    - python-software-properties
    - openssh-server
    - wget
    - curl
    - git
    - vim
    - htop
    - tree
    - zsh
    - fish

  # Download directory acts as a cache for all later 'get_url' tasks
- name: Create Download Directory
  file: path={{ download_directory }} state=directory owner=root group=root

  # https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/1242108  
- name: Apply bug fix for Ubuntu 14.04 with ZSH 5.0.2 
  script: >-
    ubuntu-14.04-zsh-5.0.2-bug-fix.sh creates=/usr/share/man/man1/zshcompctl.1.gz

- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
