---
# Install Blazegraph

- name: Download Blazegraph
  get_url: >-
    url=http://sourceforge.net/projects/bigdata/files/bigdata/{{ blazegraph_version }}/bigdata.war/download
    dest={{ download_directory }}/bigdata-{{ blazegraph_version }}.war
        
- name: Deploy Blazegraph
  command: >-
    cp {{ download_directory }}/bigdata-{{ blazegraph_version }}.war
       {{ catalina_base }}/webapps/bigdata.war
    creates={{ catalina_base }}/webapps/bigdata.war
  become: yes
  become_user: "{{ tomcat_user }}"
  notify: restart tomcat
